// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYTt2dEfgduklmmfSyNHqlaYTI-_J0SJQ',
    appId: '1:257882840853:web:9d97f825f72ded351e931c',
    messagingSenderId: '257882840853',
    projectId: 'emartgetxecommerce',
    authDomain: 'emartgetxecommerce.firebaseapp.com',
    storageBucket: 'emartgetxecommerce.appspot.com',
    measurementId: 'G-QGN9D8QPEY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIjGa91C_XmvpRZf0mvu13bPpsrCz7rqY',
    appId: '1:257882840853:android:a6117925b109ae8b1e931c',
    messagingSenderId: '257882840853',
    projectId: 'emartgetxecommerce',
    storageBucket: 'emartgetxecommerce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCETBGEXN_2zVCWB8dqi5X_yiHj3TGNmsc',
    appId: '1:257882840853:ios:debbe46ee96451f81e931c',
    messagingSenderId: '257882840853',
    projectId: 'emartgetxecommerce',
    storageBucket: 'emartgetxecommerce.appspot.com',
    iosClientId: '257882840853-qj9rad556ot2ho7m23aetq7sro21jrib.apps.googleusercontent.com',
    iosBundleId: 'com.example.emartApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCETBGEXN_2zVCWB8dqi5X_yiHj3TGNmsc',
    appId: '1:257882840853:ios:debbe46ee96451f81e931c',
    messagingSenderId: '257882840853',
    projectId: 'emartgetxecommerce',
    storageBucket: 'emartgetxecommerce.appspot.com',
    iosClientId: '257882840853-qj9rad556ot2ho7m23aetq7sro21jrib.apps.googleusercontent.com',
    iosBundleId: 'com.example.emartApp',
  );
}
